# plotting time intervals from the data generated by the webcam
from motion_detector import df
from bokeh.plotting import figure,output_file,show
from bokeh.models import HoverTool,ColumnDataSource
import pandas as pd

df["Start_string"]=pd.to_datetime(df["Start"]).dt.strftime('%Y-%m-%d %H:%M:%S')
df["End_string"]=pd.to_datetime(df["End"]).dt.strftime('%Y-%m-%d %H:%M:%S')


cds=ColumnDataSource(df)

p=figure(x_axis_type='datetime',height=250, width=800,sizing_mode='stretch_width',title="Motion Graph")
p.yaxis.minor_tick_line_color=None
p.yaxis.ticker.desired_num_ticks=1


hover=HoverTool(tooltips=[("Start","@Start_string"),("End","@End_string")])
p.add_tools(hover)

q=p.quad(left="Start",right="End",bottom=0,top=1,color="green",source=cds)

output_file("python_course/python_apps/App2_Controlling_the_Webcam_and_Detecting_Objects/Graph.html")
show(p)

